In [1]:
import pandas as pd
import numpy as np 

In [2]:
#read csv file
df_Aramco = pd.read_csv('Aramco Historical Data.csv', parse_dates=True)
df_Sabic = pd.read_csv('Sabic Historical Data.csv', parse_dates=True)
df_STC = pd.read_csv('STC Historical Data.csv', parse_dates=True)
df_Almarai = pd.read_csv('Almarai Historical Data.csv', parse_dates=True)

#merge the prices 
df_merged = pd.merge(df_Aramco, df_Sabic, on="Date", how="inner")
df_merged = df_merged[["Date", "Price_x", "Price_y"]]
df_merged = df_merged.rename(columns= {"Price_x": "Aramco", "Price_y": "Sabic"})
df_merged = pd.merge(df_merged, df_STC, on="Date", how="inner")
df_merged = df_merged[["Date", "Aramco", "Sabic", "Price"]]
df_merged = df_merged.rename(columns= {"Price": "STC"})
df_merged = pd.merge(df_merged, df_Almarai, on="Date", how="inner")
df_merged = df_merged[["Aramco", "Sabic","STC", "Price"]]
df_merged = df_merged.rename(columns= {"Price": "Almarai"})

#Calculate the return 
df_merged["Aramco_return"] = (df_merged.Aramco-df_merged.Aramco.shift(1)) / (df_merged.Aramco.shift(1))
df_merged

df_merged["Sabic_return"] = (df_merged.Sabic-df_merged.Sabic.shift(1)) / (df_merged.Sabic.shift(1))
df_merged

df_merged["STC_return"] = (df_merged.STC-df_merged.STC.shift(1)) / (df_merged.STC.shift(1))
df_merged

df_merged["Almarai_return"] = (df_merged.Almarai-df_merged.Almarai.shift(1)) / (df_merged.Almarai.shift(1))
df_merged

#The columns we want to show in the output
df_merged = df_merged[["Aramco_return", "Sabic_return", "STC_return" , "Almarai_return"]]


df=df_merged.dropna()
df

Aramco_return  Sabic_return  STC_return  Almarai_return
1         0.009333     -0.015480   -0.003436       -0.018832
2        -0.006605     -0.003145   -0.010345        0.007678
3         0.007979      0.007886    0.012195        0.003810
4        -0.003958      0.000000   -0.010327        0.009488
5         0.003974     -0.007825    0.001739       -0.005639
..             ...           ...         ...             ...
246      -0.001416     -0.007299   -0.007505       -0.012821
247       0.007092      0.008403    0.003781        0.003711
248      -0.004225     -0.001042   -0.022599        0.007394
249       0.004243      0.001043    0.019268        0.007339
250      -0.018310     -0.041667   -0.018904       -0.016393

[250 rows x 4 columns]

In [3]:
matrix_of_return_values = df.to_numpy()
matrix_of_return_values = np.asmatrix(matrix_of_return_values)
print(matrix_of_return_values)

[[ 0.00933333 -0.01547988 -0.00343643 -0.01883239]
 [-0.00660502 -0.00314465 -0.01034483  0.00767754]
 [ 0.00797872  0.00788644  0.01219512  0.00380952]
 [-0.00395778  0.         -0.01032702  0.00948767]
 [ 0.00397351 -0.00782473  0.00173913 -0.0056391 ]
 [-0.00395778  0.01735016  0.015625    0.        ]
 [-0.0013245   0.03100775  0.          0.00567108]
 [-0.00795756  0.01203008  0.0017094   0.0018797 ]
 [ 0.0013369   0.00445765  0.01706485  0.00375235]
 [-0.00133511 -0.00295858  0.00167785 -0.00934579]
 [ 0.0013369  -0.00445104 -0.01005025  0.01509434]
 [-0.00534045 -0.00447094  0.00338409  0.00185874]
 [ 0.00536913 -0.01946108 -0.01011804 -0.00742115]
 [-0.00133511  0.01068702  0.00170358  0.01495327]
 [ 0.          0.01510574  0.         -0.00552486]
 [-0.0026738  -0.00595238  0.         -0.00925926]
 [-0.0080429  -0.01047904  0.          0.        ]
 [ 0.00540541 -0.02723147  0.00340136 -0.01869159]
 [-0.00537634 -0.00155521  0.00847458  0.0152381 ]
 [-0.00135135 -0.0046729   0.00