In [1]:
# Q1
import numpy as np
A = np.array([[1,3,-2],[0,4,7],[-1,2,6]])
B = np.array([[0,1],[1,3],[2,1]])
print(np.add(A,A))

[[ 2  6 -4]
 [ 0  8 14]
 [-2  4 12]]


In [2]:
# Q2
print(A.T)
print(B.T)

[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]
[[0 1 2]
 [1 3 1]]


In [3]:
#Q3
A=np.asmatrix(A)
print(A.I)

[[-0.52631579  1.15789474 -1.52631579]
 [ 0.36842105 -0.21052632  0.36842105]
 [-0.21052632  0.26315789 -0.21052632]]


In [4]:
# Q4 
print(np.asmatrix(A) * np.asmatrix(B))
print(np.dot(A,B))

[[-1  8]
 [18 19]
 [14 11]]
[[-1  8]
 [18 19]
 [14 11]]


In [5]:
# Q5
C = np.reshape(B,(2,3))
print (C)

[[0 1 1]
 [3 2 1]]


In [6]:
# Q6

print(np. dot(C,A))

[[-1  6 13]
 [ 2 19 14]]


In [7]:
#Q7
D = np.array(A)
print (np.where(D ==1,-1,D))

[[-1  3 -2]
 [ 0  4  7]
 [-1  2  6]]


In [8]:
#Q8
print(A)
print(np.sum(A, axis = 1))

[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
[[ 2]
 [11]
 [ 7]]


In [9]:
#Q9
print(A)
print(np.mean(A, axis = 0))


[[ 1  3 -2]
 [ 0  4  7]
 [-1  2  6]]
[[0.         3.         3.66666667]]


In [10]:
#Q10
print(B)
print(np.sqrt(B))

[[0 1]
 [1 3]
 [2 1]]
[[0.         1.        ]
 [1.         1.73205081]
 [1.41421356 1.        ]]
