In [12]:
# Q1
import numpy as np
A = np.array([[1,3,-2],[0,4,7],[-1,2,6]])
B = np.array([[0,1],[1,3],[2,1]])
print (np.sum(A))

20


In [29]:
# Q2
T = np.transpose(A)
print (T)
W = np.transpose(B)
print (W)

[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]
[[0 1 2]
 [1 3 1]]


In [3]:
#Q3
print (np.asmatrix(A)*np.asmatrix(A).I)

[[ 1.00000000e+00  1.11022302e-16  5.55111512e-17]
 [-1.94289029e-16  1.00000000e+00 -1.94289029e-16]
 [-1.66533454e-16 -1.11022302e-16  1.00000000e+00]]


In [4]:
# Q4 
print(np. dot(A,B))

[[-1  8]
 [18 19]
 [14 11]]


In [5]:
# Q5
C = np.reshape(B,(2,3))
print (C)

[[0 1 1]
 [3 2 1]]


In [6]:
# Q6

print(np. dot(C,A))

[[-1  6 13]
 [ 2 19 14]]


In [7]:
#Q7
D = np.array(A)
print (np.where(D ==1,-1,D))

[[-1  3 -2]
 [ 0  4  7]
 [-1  2  6]]


In [33]:
#Q8
#print(np.sum(A,axis=0))#output [0 9 11]
s = np.matrix([[0,9,11]])
print(s)

[[ 0  9 11]]


In [35]:
#Q9
g = np.matrix([[1,0,-1], [3,4,2], [-2,7,6]])
print(g)


[[ 1  0 -1]
 [ 3  4  2]
 [-2  7  6]]


In [30]:
#Q10
print(np.sqrt(B))

[ 0  9 11]
